=== PearCoding/Ignis/docs/refs/ignis.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "ignis.schema.json",
    "title": "Ignis Scene Description",
    "description": "Ignis scene description language",
    "type": "object",
    "properties": {
        "technique": {
            "$ref": "#/definitions/Technique"
        },
        "camera": {
            "$ref": "#/definitions/Camera"
        },
        "film": {
            "$ref": "#/definitions/Film"
        },
        "externals": {
            "description": "List of external files",
            "type": "array",
            "items": {
                "$ref": "#/definitions/External"
            },
            "uniqueItems": true
        },
        "textures": {
            "description": "List of textures",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Texture"
            },
            "uniqueItems": true
        },
        "bsdfs": {
            "description": "List of bsdfs",
            "type": "array",
            "items": {
                "$ref": "#/definitions/BSDF"
            },
            "uniqueItems": true
        },
        "media": {
            "description": "List of volumes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Medium"
            },
            "uniqueItems": true
        },
        "shapes": {
            "description": "List of shapes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Shape"
            },
            "uniqueItems": true
        },
        "entities": {
            "description": "List of entities",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Entity"
            },
            "uniqueItems": true
        },
        "lights": {
            "description": "List of lights",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Light"
            },
            "uniqueItems": true
        }
    },
    "definitions": {
        "External": {
            "description": "External properties",
            "type": "object",
            "required": [
                "filename"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Technique": {
            "description": "Technique properties",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Camera": {
            "description": "Camera properties",
            "type": "object",
            "required": [],
            "properties": {
                "type": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                }
            },
            "additionalProperties": true
        },
        "Film": {
            "description": "Film/Image properties",
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "size": {
                    "$ref": "#/definitions/Size"
                },
                "sampler": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Texture": {
            "description": "Texture properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "BSDF": {
            "description": "BSDF properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Medium": {
            "description": "Medium/Volume properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Shape": {
            "description": "Shape properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Entity": {
            "description": "Entity properties",
            "type": "object",
            "required": [
                "name",
                "shape"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                },
                "bsdf": {
                    "type": "string"
                },
                "shape": {
                    "type": "string"
                },
                "inner_medium": {
                    "type": "string"
                },
                "outer_medium": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Light": {
            "description": "Light properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Transform": {
            "description": "Transform properties (proxy)",
            "oneOf": [
                {
                    "$ref": "#/definitions/TransformObject"
                },
                {
                    "$ref": "#/definitions/Matrix3x3"
                },
                {
                    "$ref": "#/definitions/Matrix3x4"
                },
                {
                    "$ref": "#/definitions/Matrix4x4"
                }
            ]
        },
        "TransformObject": {
            "description": "Transform properties",
            "type": "array",
            "required": [],
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "translate": {
                            "$ref": "#/definitions/Vector3"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "rotate": {
                            "$ref": "#/definitions/Vector4"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "scale": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Vector3"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "matrix": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Matrix3x3"
                                },
                                {
                                    "$ref": "#/definitions/Matrix3x4"
                                },
                                {
                                    "$ref": "#/definitions/Matrix4x4"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "lookat": {
                            "$ref": "#/definitions/Lookat"
                        }
                    }
                }
            ]
        },
        "Lookat": {
            "description": "Lookat properties",
            "type": "object",
            "required": [],
            "properties": {
                "origin": {
                    "$ref": "#/definitions/Vector3"
                },
                "up": {
                    "$ref": "#/definitions/Vector3"
                },
                "target": {
                    "$ref": "#/definitions/Vector3"
                },
                "direction": {
                    "$ref": "#/definitions/Vector3"
                }
            }
        },
        "Size": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "Vector3": {
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {
                "type": "number"
            }
        },
        "Vector4": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x3": {
            "type": "array",
            "minItems": 9,
            "maxItems": 9,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x4": {
            "type": "array",
            "minItems": 12,
            "maxItems": 12,
            "items": {
                "type": "number"
            }
        },
        "Matrix4x4": {
            "type": "array",
            "minItems": 16,
            "maxItems": 16,
            "items": {
                "type": "number"
            }
        }
    }
}

=== PearCoding/Ignis/scenes/gauss_lobe.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,1,0,0, 0,0,1,-4, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Lobe", "reflectance": 0.8}
	],
	"shapes": [
		{"type":"gauss_lobe", "name":"Lobe", "direction":[0,1,1], "x_axis": [-1,0,0], "y_axis": [0,0,1], "sigma_theta": 0.35, "sigma_phi": 0.4, "anisotropy": 0.0, "scale": 1},
		{"type":"sphere", "name":"Origin", "radius": 0.1}
	],
	"entities": [
		{"name":"Lobe","shape":"Lobe","bsdf":"mat-Lobe"},
		{"name":"Origin","shape":"Origin","bsdf":"mat-Lobe"}
	],
	"lights": [
		{"type":"constant", "name":"Environment", "radiance":1}
	]
}

=== PearCoding/Ignis/scenes/plane-plane.json
{
  "technique": {
    "type": "path",
    "max_depth": 6
  },
  "camera": {
    "type": "perspective",
    "transform": [{"lookat": {"direction":[0,0,1], "origin": [0,0,-2], "up": [0,1,0]}}],
    "fov": 40
  },
  "film": {
    "size": [1024, 1024]
  },
  "textures": [],
  "bsdfs": [
    {
      "name": "white",
      "type": "diffuse",
      "reflectance": [1,1,1]
    }
  ],
  "shapes": [
		{"type":"rectangle", "name":"plane", "width":1, "height":1, "transform": [{"rotate": [90,0,0]}]}
  ],
  "entities": [
    {
      "name": "bottom",
      "shape": "plane",
      "bsdf": "white",
      "transform": [{"translate": [0,-0.5,0]}, {"rotate": [180,0,0]}]
    },
    {
      "name": "top",
      "shape": "plane",
      "bsdf": "white",
      "transform": [{"translate": [0,0.5,0]}]
    },
    {
      "name": "back",
      "shape": "plane",
      "bsdf": "white",
      "transform": [{"translate": [0,0,0.5]}, {"rotate": [90,0,0]}]
    }
  ],
  "lights": [
    {
      "name": "light",
      "type": "area",
      "entity": "top",
      "radiance": [1,1,1]
    }
  ]
}

=== PearCoding/Ignis/scenes/gauss.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,1,0,0, 0,0,1,-4, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Lobe", "reflectance": 0.8}
	],
	"shapes": [
		{"type":"gauss", "name":"Lobe", "normal":[0,1,0], "sigma": 0.35, "radius_scale": 1, "height": 1}
	],
	"entities": [
		{"name":"Lobe","shape":"Lobe", "bsdf":"mat-Lobe"}
	],
	"lights": [
		{"type":"constant", "name":"Environment", "radiance":1}
	]
}

=== PearCoding/Ignis/scenes/primitive_scene_aov.json
{
	"technique": {
		"type": "path",
		"max_depth": 2,
		"aov_normals": true,
		"aov_mis": true,
		"aov_stats": true
	},
	"camera": {
		"type": "perspective",
		"fov": 60,
		"near_clip": 0.01,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,0,1,-8, 0,1,0,0 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"externals": [
		{"filename": "primitive_scene_data.json"}
	]
}

=== PearCoding/Ignis/scenes/emissive_sphere.json
{
	"technique": {
		"type": "path",
		"max_depth": 2
	},
	"camera": {
		"type": "perspective",
		"fov": 60,
		"near_clip": 0.01,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,0,1,-8, 0,1,0,0 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "ground", "reflectance":[0.8, 0.8, 0.8]},
		{"type":"diffuse", "name": "object", "reflectance":[0.95, 0.95, 0.95]}
	],
	"shapes": [
		{"type":"rectangle", "name":"Bottom", "width":10, "height":8},
		{"type":"icosphere", "name":"IcoSphere"}
	],
	"entities": [
		{"name":"Bottom","shape":"Bottom", "bsdf":"ground", "transform": [{"translate":[0,0,-1]}]},
		{"name":"IcoSphere","shape":"IcoSphere", "bsdf":"object"}
	],
	"lights": [
		{"type":"area", "name":"Light", "entity": "IcoSphere", "radiance":[1,1,1]}
	]
}

=== PearCoding/Ignis/scenes/evaluation/cycles-roughness-base.json
{
  "technique": {
    "type": "path",
    "max_depth": 32
  },
  "camera": {
    "type": "perspective",
    "fov": 39.597752709049864,
    "near_clip": 0.10000000149011612,
    "far_clip": 100.0,
    "transform": [
      -0.9521293640136719,
      -0.012801197357475758,
      -0.30542710423469543,
      1.3688405752182007,
      -0.3056952655315399,
      0.03987182304263115,
      0.9512941837310791,
      -4.263437271118164,
      2.2472998750799889e-07,
      0.9991227984428406,
      -0.041876357048749924,
      1.4294512271881104,
      0.0,
      0.0,
      0.0,
      1.0
    ]
  },
  "film": {
    "size": [
      256.0,
      256.0
    ]
  },
  "shapes": [
    {
      "type": "ply",
      "name": "GroundPlane",
      "filename": "meshes/GroundPlane.ply"
    },
    {
      "type": "ply",
      "name": "Mesh",
      "filename": "meshes/Mesh.ply"
    }
  ],
  "bsdfs": [
    {
      "type": "diffuse",
      "name": "Ground",
      "reflectance": "select(checkerboard(uvw * 10.0) == 1, color(0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0), color(0.20000000298023224, 0.20000000298023224, 0.20000000298023224, 1.0))"
    }
  ],
  "entities": [
    {
      "name": "GroundPlane-GroundPlane",
      "shape": "GroundPlane",
      "bsdf": "Ground",
      "transform": [
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0
      ]
    },
    {
      "name": "IcosphereHQ-Mesh",
      "shape": "Mesh",
      "bsdf": "Material",
      "transform": [
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        0.0,
        0.0,
        0.0,
        1.0
      ]
    }
  ],
  "lights": [
    {
      "type": "point",
      "name": "Light",
      "position": [
        1.699600100517273,
        -1.2251337766647339,
        1.8338091373443604
      ],
      "power": [
        1000.0,
        1000.0,
        1000.0
      ]
    }
  ],
  "textures": [
    {
      "type": "image",
      "name": "_tex_0",
      "filename": "../textures/grid_weight.png",
      "wrap_mode": "repeat",
      "filter_type": "bilinear",
      "linear": false
    }
  ]
}

=== PearCoding/Ignis/scenes/evaluation/cycles-mix-trans-trans.json
{
  "technique": {
    "type": "path",
    "max_depth": 4,
    "clamp": 0.0
  },
  "camera": {
    "type": "perspective",
    "fov": 39.597752709049864,
    "near_clip": 0.10000000149011612,
    "far_clip": 100.0,
    "transform": [
      -1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -1.0,
      5.0,
      0.0,
      0.0,
      0.0,
      1.0
    ]
  },
  "film": {
    "size": [
      256.0,
      256.0
    ]
  },
  "shapes": [
    {
      "type": "ply",
      "name": "Plane.001",
      "filename": "meshes/Plane.001.ply"
    }
  ],
  "bsdfs": [
    {
      "type": "transparent",
      "name": "Plane__1",
      "color": "color(1.0, 0.08654338866472244, 0.1086520180106163, 1.0)"
    },
    {
      "type": "transparent",
      "name": "Plane__2",
      "color": "color(0.15525473654270172, 0.38431301712989807, 1.0, 1.0)"
    },
    {
      "type": "blend",
      "name": "Plane",
      "first": "Plane__1",
      "second": "Plane__2",
      "weight": 0.5
    }
  ],
  "entities": [
    {
      "name": "Plane.001-Plane.001",
      "shape": "Plane.001",
      "bsdf": "Plane",
      "transform": [
        0.7071068286895752,
        0.7071067690849304,
        0.0,
        0.0,
        -0.7071067690849304,
        0.7071068286895752,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.699999988079071,
        0.0,
        0.0,
        0.0,
        1.0
      ]
    }
  ],
  "lights": [
    {
      "type": "env",
      "name": "__scene_world",
      "radiance": "color(0.20000000298023224, 0.20000000298023224, 0.20000000298023224, 1.0)",
      "transform": [
        0,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0
      ]
    }
  ]
}

=== PearCoding/Ignis/scenes/environment_map.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "fishlens",
		"mode": "full",
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [{"lookat": {"direction":[0,1,0]}}]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "image",
			"name": "env",
			"filename": "textures/environment/phalzer_forest_01_4k.exr"
		}
	],
	"lights": [
		{"type":"env", "name":"Environment", "radiance":"env"}
	]
}
