=== PearCoding/Ignis/docs/refs/ignis.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "ignis.schema.json",
    "title": "Ignis Scene Description",
    "description": "Ignis scene description language",
    "type": "object",
    "properties": {
        "technique": {
            "$ref": "#/definitions/Technique"
        },
        "camera": {
            "$ref": "#/definitions/Camera"
        },
        "film": {
            "$ref": "#/definitions/Film"
        },
        "externals": {
            "description": "List of external files",
            "type": "array",
            "items": {
                "$ref": "#/definitions/External"
            },
            "uniqueItems": true
        },
        "textures": {
            "description": "List of textures",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Texture"
            },
            "uniqueItems": true
        },
        "bsdfs": {
            "description": "List of bsdfs",
            "type": "array",
            "items": {
                "$ref": "#/definitions/BSDF"
            },
            "uniqueItems": true
        },
        "media": {
            "description": "List of volumes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Medium"
            },
            "uniqueItems": true
        },
        "shapes": {
            "description": "List of shapes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Shape"
            },
            "uniqueItems": true
        },
        "entities": {
            "description": "List of entities",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Entity"
            },
            "uniqueItems": true
        },
        "lights": {
            "description": "List of lights",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Light"
            },
            "uniqueItems": true
        }
    },
    "definitions": {
        "External": {
            "description": "External properties",
            "type": "object",
            "required": [
                "filename"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Technique": {
            "description": "Technique properties",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Camera": {
            "description": "Camera properties",
            "type": "object",
            "required": [],
            "properties": {
                "type": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                }
            },
            "additionalProperties": true
        },
        "Film": {
            "description": "Film/Image properties",
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "size": {
                    "$ref": "#/definitions/Size"
                },
                "sampler": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Texture": {
            "description": "Texture properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "BSDF": {
            "description": "BSDF properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Medium": {
            "description": "Medium/Volume properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Shape": {
            "description": "Shape properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Entity": {
            "description": "Entity properties",
            "type": "object",
            "required": [
                "name",
                "shape"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                },
                "bsdf": {
                    "type": "string"
                },
                "shape": {
                    "type": "string"
                },
                "inner_medium": {
                    "type": "string"
                },
                "outer_medium": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Light": {
            "description": "Light properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Transform": {
            "description": "Transform properties (proxy)",
            "oneOf": [
                {
                    "$ref": "#/definitions/TransformObject"
                },
                {
                    "$ref": "#/definitions/Matrix3x3"
                },
                {
                    "$ref": "#/definitions/Matrix3x4"
                },
                {
                    "$ref": "#/definitions/Matrix4x4"
                }
            ]
        },
        "TransformObject": {
            "description": "Transform properties",
            "type": "array",
            "required": [],
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "translate": {
                            "$ref": "#/definitions/Vector3"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "rotate": {
                            "$ref": "#/definitions/Vector4"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "scale": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Vector3"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "matrix": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Matrix3x3"
                                },
                                {
                                    "$ref": "#/definitions/Matrix3x4"
                                },
                                {
                                    "$ref": "#/definitions/Matrix4x4"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "lookat": {
                            "$ref": "#/definitions/Lookat"
                        }
                    }
                }
            ]
        },
        "Lookat": {
            "description": "Lookat properties",
            "type": "object",
            "required": [],
            "properties": {
                "origin": {
                    "$ref": "#/definitions/Vector3"
                },
                "up": {
                    "$ref": "#/definitions/Vector3"
                },
                "target": {
                    "$ref": "#/definitions/Vector3"
                },
                "direction": {
                    "$ref": "#/definitions/Vector3"
                }
            }
        },
        "Size": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "Vector3": {
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {
                "type": "number"
            }
        },
        "Vector4": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x3": {
            "type": "array",
            "minItems": 9,
            "maxItems": 9,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x4": {
            "type": "array",
            "minItems": 12,
            "maxItems": 12,
            "items": {
                "type": "number"
            }
        },
        "Matrix4x4": {
            "type": "array",
            "minItems": 16,
            "maxItems": 16,
            "items": {
                "type": "number"
            }
        }
    }
}

=== PearCoding/Ignis/scenes/evaluation/cycles-bumpmap.json
{
  "technique": {
    "type": "path",
    "max_depth": 32,
    "clamp": 100.0
  },
  "camera": {
    "type": "perspective",
    "fov": 39.597752709049864,
    "near_clip": 0.10000000149011612,
    "far_clip": 100.0,
    "transform": [
      -0.9521293640136719,
      -0.012801197357475758,
      -0.30542710423469543,
      1.3688405752182007,
      -0.3056952655315399,
      0.03987182304263115,
      0.9512941837310791,
      -4.263437271118164,
      2.2472998750799889e-07,
      0.9991227984428406,
      -0.041876357048749924,
      1.4294512271881104,
      0.0,
      0.0,
      0.0,
      1.0
    ]
  },
  "film": {
    "size": [
      256.0,
      256.0
    ]
  },
  "shapes": [
    {
      "type": "ply",
      "name": "GroundPlane",
      "filename": "meshes/GroundPlane.ply"
    },
    {
      "type": "ply",
      "name": "IcosphereHQ",
      "filename": "meshes/IcosphereHQ.ply"
    }
  ],
  "bsdfs": [
    {
      "type": "diffuse",
      "name": "__bsdf_black",
      "reflectance": 0
    },
    {
      "type": "diffuse",
      "name": "__bsdf_error",
      "reflectance": [
        1,
        0.75,
        0.8
      ]
    },
    {
      "type": "diffuse",
      "name": "Ground",
      "reflectance": "select(checkerboard(uvw * 10.0) == 1, color(0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0), color(0.20000000298023224, 0.20000000298023224, 0.20000000298023224, 1.0))"
    },
    {
      "type": "principled",
      "name": "Material_inner",
      "base_color": "mix(_tex_0((uvw).xy), max(_tex_0((uvw).xy), color(0.0, 0.002233547391369939, 0.5, 1.0)), clamp(1.0,0,1))",
      "metallic": 0.949999988079071,
      "roughness": 0.1599999964237213,
      "anisotropic": 0.0,
      "sheen": 0.0,
      "sheen_tint": 0.5,
      "clearcoat": 0.0,
      "clearcoat_roughness": 0.029999999329447746,
      "flatness": 0.0,
      "specular_transmission": 0.0,
      "specular_tint": 0.0,
      "ior": 1.7887885053796064
    },
    {
      "type": "transform",
      "name": "Material",
      "bsdf": "Material_inner",
      "normal": "ensure_valid_reflection(Ng, V, bump(N, Nx, Ny, 1.0, (((luminance(_tex_0(((vec3(0.001, 0, 0) + uvw)).xy)))-(luminance(_tex_0((uvw).xy))))/0.001), (((luminance(_tex_0(((vec3(0.0, 0.001, 0) + uvw)).xy)))-(luminance(_tex_0((uvw).xy))))/0.001)))"
    }
  ],
  "entities": [
    {
      "name": "GroundPlane-GroundPlane",
      "shape": "GroundPlane",
      "bsdf": "Ground",
      "transform": [
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "shadow_visible": true
    },
    {
      "name": "IcosphereHQ-IcosphereHQ",
      "shape": "IcosphereHQ",
      "bsdf": "Material",
      "transform": [
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "shadow_visible": true
    }
  ],
  "lights": [
    {
      "type": "point",
      "name": "Light",
      "position": [
        1.699600100517273,
        -1.2251337766647339,
        1.8338091373443604
      ],
      "power": [
        1000.0,
        1000.0,
        1000.0
      ]
    }
  ],
  "textures": [
    {
      "type": "image",
      "name": "_tex_0",
      "filename": "../textures/grid_weight.png",
      "wrap_mode": "repeat",
      "filter_type": "bilinear",
      "linear": false
    }
  ]
}

=== PearCoding/Ignis/scenes/masked_plane.json
{
	"technique": {
		"type": "path",
		"max_depth": 4
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ -1,0,0,0, 0,1,0,0, 0,0,-1,15, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "env",
			"filename": "textures/environment/phalzer_forest_01_4k.exr"
		},
		{
			"type": "checkerboard",
			"name": "check",
			"scale_x": 10,
			"scale_y": 10,
			"color0": [0,0,0],
			"color1": [1,1,1]
		},
		{
			"type": "bitmap",
			"name": "mask",
			"filename": "textures/mask.png"
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Fallback"},
		{"type":"conductor", "name": "mat-BackInner", "specular_reflectance": [0.7, 0.4, 0.04]},
		{"type":"bumpmap", "name": "mat-Back", "bsdf":"mat-BackInner", "map":"perlin(20*uv)*voronoi(15*uv)*0.02"},
		{"type":"diffuse", "name": "mat-Floor", "reflectance":"check(uv*2*sin(uv.x*4*Pi) + P.xy*avg(uv) - vec2(Eps, E)) * select(uv.x > noise(sum(uv)), color(1,0.5,0), color(0,0.5,1))"},
		{"type":"diffuse", "name": "mat-PlaneSurface", "reflectance":[0, 0.552, 0.721]},
		{"type":"mask", "name": "mat-Plane", "bsdf": "mat-PlaneSurface", "weight":"mask.r"}
	],
	"shapes": [
		{"type":"rectangle", "name":"Floor", "width": 10, "height": 10},
		{"type":"rectangle", "name":"Back", "width": 10, "height": 5},
		{"type":"box", "name":"Plane", "width": 4, "height": 4, "depth": 0.1}
	],
	"entities": [
		{"name":"Floor","shape":"Floor", "bsdf":"mat-Floor"},
		{"name":"Back","shape":"Back", "bsdf":"mat-Back", "transform": [{"rotate": [90,0,0]}, {"translate": [0,2.5,-5]}]},
		{"name":"Plane","shape":"Plane", "bsdf":"mat-Plane", "transform": [{"rotate": [0,0,45]}, {"translate": [0,0,2]}]}
	],
	"lights": [
		{"type":"env", "name":"Sky", "radiance": "env", "transform": [1,0,0, 0,0,1, 0,1,0]}
	]
}

=== PearCoding/Ignis/scenes/evaluation/cbox-base.json
{
  "camera": {
    "type": "perspective",
    "transform": [1, 0, 0, 278, 0, 1, 0, 273, 0, 0, 1, -800, 0, 0, 0, 1],
    "fov": 39.3077,
    "far_clip": 2800,
    "near_clip": 10
  },
  "film": {
    "size": [256, 256]
  },
  "textures": [],
  "bsdfs": [
    {
      "name": "__bsdf_0",
      "type": "diffuse",
      "reflectance": [0.45, 0.3, 0.9]
    },
    {
      "name": "__bsdf_1",
      "type": "diffuse",
      "reflectance": [0.885809, 0.698859, 0.666422]
    },
    {
      "name": "__bsdf_2",
      "type": "diffuse",
      "reflectance": [0.570068, 0.0430135, 0.0443706]
    },
    {
      "name": "__bsdf_3",
      "type": "diffuse",
      "reflectance": [0.105421, 0.37798, 0.076425]
    },
    {
      "name": "__bsdf_4",
      "type": "diffuse",
      "reflectance": [0.936461, 0.740433, 0.705267]
    }
  ],
  "shapes": [
    {
      "name": "__shape_0",
      "type": "obj",
      "transform": [1, 0, 0, 0, 0, 1, 0, -0.5, 0, 0, 1, 0, 0, 0, 0, 1],
      "filename": "meshes/cbox_luminaire.obj"
    },
    {
      "name": "__shape_1",
      "type": "obj",
      "filename": "meshes/cbox_floor.obj"
    },
    {
      "name": "__shape_2",
      "type": "obj",
      "filename": "meshes/cbox_ceiling.obj"
    },
    {
      "name": "__shape_3",
      "type": "obj",
      "filename": "meshes/cbox_back.obj"     
    },
    {
      "name": "__shape_4",
      "type": "obj",
      "filename": "meshes/cbox_greenwall.obj"
    },
    {
      "name": "__shape_5",
      "type": "obj",
      "filename": "meshes/cbox_redwall.obj"
    },
    {
      "name": "__shape_6",
      "type": "obj",
      "filename": "meshes/cbox_smallbox.obj"
    },
    {
      "name": "__shape_7",
      "type": "obj",
      "filename": "meshes/cbox_largebox.obj"
    }
  ],
  "entities": [
    {
      "name": "__entity_0",
      "shape": "__shape_0",
      "bsdf": "__bsdf_4"
    },
    {
      "name": "__entity_1",
      "shape": "__shape_1",
      "bsdf": "__bsdf_1"
    },
    {
      "name": "__entity_2",
      "shape": "__shape_2",
      "bsdf": "__bsdf_1"
    },
    {
      "name": "__entity_3",
      "shape": "__shape_3",
      "bsdf": "__bsdf_1"
    },
    {
      "name": "__entity_4",
      "shape": "__shape_4",
      "bsdf": "__bsdf_3"
    },
    {
      "name": "__entity_5",
      "shape": "__shape_5",
      "bsdf": "__bsdf_2"
    },
    {
      "name": "__entity_6",
      "shape": "__shape_6",
      "bsdf": "__bsdf_0"
    },
    {
      "name": "__entity_7",
      "shape": "__shape_7",
      "bsdf": "__bsdf_0"
    }
  ],
  "lights": [
    {
      "name": "__light_0",
      "type": "area",
      "entity": "__entity_0",
      "radiance": [18.387, 10.9873, 2.75357]
    }
  ]
}

=== PearCoding/Ignis/scenes/evaluation/cycles-lights.json
{
  "technique": {
    "type": "path",
    "max_depth": 32,
    "clamp": 0.0
  },
  "camera": {
    "type": "perspective",
    "fov": 39.597752709049864,
    "near_clip": 0.10000000149011612,
    "far_clip": 100.0,
    "transform": [
      -1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -1.0,
      12.490668296813965,
      0.0,
      0.0,
      0.0,
      1.0
    ]
  },
  "film": {
    "size": [
      256.0,
      256.0
    ]
  },
  "shapes": [
    {
      "type": "ply",
      "name": "GroundPlane",
      "filename": "meshes/GroundPlane.ply"
    },
    {
      "type": "rectangle",
      "name": "Light.002-shape",
      "width": 0.10000000149011612,
      "height": 0.10000000149011612,
      "flip_normals": true
    }
  ],
  "bsdfs": [
    {
      "type": "diffuse",
      "name": "__bsdf_black",
      "reflectance": 0
    },
    {
      "type": "diffuse",
      "name": "__bsdf_error",
      "reflectance": [
        1,
        0.75,
        0.8
      ]
    },
    {
      "type": "diffuse",
      "name": "Ground",
      "reflectance": "select(checkerboard(uvw * 10.0) == 1, color(0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0), color(0.20000000298023224, 0.20000000298023224, 0.20000000298023224, 1.0))"
    }
  ],
  "entities": [
    {
      "name": "GroundPlane-GroundPlane",
      "shape": "GroundPlane",
      "bsdf": "Ground",
      "transform": [
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "shadow_visible": true
    },
    {
      "name": "Light.002",
      "shape": "Light.002-shape",
      "bsdf": "__bsdf_black",
      "transform": [
        0.36456236243247986,
        0.750999927520752,
        -0.5505391955375671,
        -1.0198211669921875,
        -0.4070475101470947,
        0.6602750420570374,
        0.6311490535736084,
        1.6631189584732056,
        0.8375002145767212,
        -0.005997585132718086,
        0.5464040637016296,
        2.5988268852233887,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "camera_visible": false,
      "bounce_visible": true
    }
  ],
  "lights": [
    {
      "type": "point",
      "name": "Light",
      "position": [
        2.7762451171875,
        2.9477834701538086,
        3.067789316177368
      ],
      "intensity": [
        0.0,
        0.0,
        1000.0
      ]
    },
    {
      "type": "spot",
      "name": "Light.001",
      "position": [
        -2.9966487884521484,
        -0.22661614418029785,
        3.305354356765747
      ],
      "direction": [
        0.7042534351348877,
        -0.13068173825740814,
        -0.6978176236152649
      ],
      "intensity": [
        0.0,
        1000.0,
        0.0
      ],
      "cutoff": 37.49999933598528,
      "falloff": 34.477318400880165
    },
    {
      "type": "area",
      "name": "Light.002",
      "entity": "Light.002",
      "radiance": [
        24999.99925494196,
        0.0,
        0.0
      ]
    }
  ]
}

=== PearCoding/Ignis/scenes/box_enclosed_env.json
{
	"technique": {
		"type": "path",
		"max_depth": 6
	},
	"camera": {
		"type": "fisheye",
		"near_clip": 0.1,
		"far_clip": 100
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "Material", "reflectance":[0.8,0.8,0.8]}
	],
	"shapes": [
		{"type":"cube", "name":"Cube"}
	],
	"entities": [
		{"name":"Bottom","shape":"Cube", "bsdf":"Material"}
	],
	"lights": [
		{"type":"env", "name":"Env", "radiance":[100,100,100]}
	]
}

=== PearCoding/Ignis/scenes/pillar_scene.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 39.597755,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ -1,0,0,0, 0,1,0,0, 0,0,-1,3.849529, 0,0,0,1 ]
	},
	"film": {
		"type": "hdr",
		"size": [1000, 1000],
        "spp": 4
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "tex",
			"filename": "textures/bumpmap.png",
			"filter_type": "trilinear"
		},
		{
			"type": "checkerboard",
			"name": "check",
			"scale_x": 10,
			"scale_y": 5,
			"color0": [0.3,0.3,0.3],
			"color1": [1,1,1]
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Ground", "reflectance":"check"},
		{"type":"roughconductor", "name": "mat-Inner", "reflectance":[1,1,1], "alpha":0.16},
		{"type":"bumpmap", "name": "mat-Pillar", "bsdf":"mat-Inner", "map":"tex", "strength":0.2}
	],
	"shapes": [
		{"type":"ply", "name":"Bottom", "filename":"meshes/Bottom.ply"},
		{"type":"ply", "name":"Pillar", "filename":"meshes/Pillar.ply"}
	],
	"entities": [
		{"name":"Bottom","shape":"Bottom", "bsdf":"mat-Ground"},
		{"name":"Pillar","shape":"Pillar", "bsdf":"mat-Pillar", "transform": [ 0.25,0,0,0, 0,0.5,0,-1, 0,0,0.25,0, 0,0,0,1 ]}
	],
	"lights": [
		{"type":"sky", "name":"Sky"},
		{"type":"sun", "name":"Sun", "sun_direction":[0.4082482904638631,0.4082482904638631,0.8164965809277261]}
	]
}

=== PearCoding/Ignis/scenes/disp_test.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 39.597755,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ -1,0,0,0, 0,1,0,0, 0,0,-1,3.849529, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "tex",
			"filename": "textures/bumpmap.png",
			"filter_type": "trilinear"
		},
		{
			"type": "checkerboard",
			"name": "check",
			"scale_x": 10,
			"scale_y": 5,
			"color0": [0.3,0.3,0.3],
			"color1": [1,1,1]
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Sphere", "reflectance":"check"}
	],
	"shapes": [
		{"type":"uvsphere", "name":"Sphere"}
	],
	"entities": [
		{"name":"Sphere","shape":"Sphere", "bsdf":"mat-Sphere"}
	],
	"lights": [
		{"type":"sky", "name":"Sky"},
		{"type":"sun", "name":"Sun", "sun_direction":[0.4082482904638631,0.4082482904638631,0.8164965809277261]}
	]
}

=== PearCoding/Ignis/scenes/inverted_entity.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,1,0,0, 0,0,1,-4, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Sphere", "reflectance": 0.8}
	],
	"shapes": [
		{"type":"ply", "name":"Sphere", "filename":"meshes/Sphere.ply", "flip_normals": true}
	],
	"entities": [
		{"name":"Sphere","shape":"Sphere", "bsdf":"mat-Sphere", "transform": [-1,0,0, 0,-1,0, 0,0,-1]}
	],
	"lights": [
		{"type":"constant", "name":"Environment", "radiance":1}
	]
}
