=== PearCoding/Ignis/docs/refs/ignis.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "ignis.schema.json",
    "title": "Ignis Scene Description",
    "description": "Ignis scene description language",
    "type": "object",
    "properties": {
        "technique": {
            "$ref": "#/definitions/Technique"
        },
        "camera": {
            "$ref": "#/definitions/Camera"
        },
        "film": {
            "$ref": "#/definitions/Film"
        },
        "externals": {
            "description": "List of external files",
            "type": "array",
            "items": {
                "$ref": "#/definitions/External"
            },
            "uniqueItems": true
        },
        "textures": {
            "description": "List of textures",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Texture"
            },
            "uniqueItems": true
        },
        "bsdfs": {
            "description": "List of bsdfs",
            "type": "array",
            "items": {
                "$ref": "#/definitions/BSDF"
            },
            "uniqueItems": true
        },
        "media": {
            "description": "List of volumes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Medium"
            },
            "uniqueItems": true
        },
        "shapes": {
            "description": "List of shapes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Shape"
            },
            "uniqueItems": true
        },
        "entities": {
            "description": "List of entities",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Entity"
            },
            "uniqueItems": true
        },
        "lights": {
            "description": "List of lights",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Light"
            },
            "uniqueItems": true
        }
    },
    "definitions": {
        "External": {
            "description": "External properties",
            "type": "object",
            "required": [
                "filename"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Technique": {
            "description": "Technique properties",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Camera": {
            "description": "Camera properties",
            "type": "object",
            "required": [],
            "properties": {
                "type": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                }
            },
            "additionalProperties": true
        },
        "Film": {
            "description": "Film/Image properties",
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "size": {
                    "$ref": "#/definitions/Size"
                },
                "sampler": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Texture": {
            "description": "Texture properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "BSDF": {
            "description": "BSDF properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Medium": {
            "description": "Medium/Volume properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Shape": {
            "description": "Shape properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Entity": {
            "description": "Entity properties",
            "type": "object",
            "required": [
                "name",
                "shape"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "transform": {
                    "$ref": "#/definitions/Transform"
                },
                "bsdf": {
                    "type": "string"
                },
                "shape": {
                    "type": "string"
                },
                "inner_medium": {
                    "type": "string"
                },
                "outer_medium": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Light": {
            "description": "Light properties",
            "type": "object",
            "required": [
                "type",
                "name"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "Transform": {
            "description": "Transform properties (proxy)",
            "oneOf": [
                {
                    "$ref": "#/definitions/TransformObject"
                },
                {
                    "$ref": "#/definitions/Matrix3x3"
                },
                {
                    "$ref": "#/definitions/Matrix3x4"
                },
                {
                    "$ref": "#/definitions/Matrix4x4"
                }
            ]
        },
        "TransformObject": {
            "description": "Transform properties",
            "type": "array",
            "required": [],
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "translate": {
                            "$ref": "#/definitions/Vector3"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "rotate": {
                            "$ref": "#/definitions/Vector4"
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "scale": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Vector3"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "matrix": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/Matrix3x3"
                                },
                                {
                                    "$ref": "#/definitions/Matrix3x4"
                                },
                                {
                                    "$ref": "#/definitions/Matrix4x4"
                                }
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "lookat": {
                            "$ref": "#/definitions/Lookat"
                        }
                    }
                }
            ]
        },
        "Lookat": {
            "description": "Lookat properties",
            "type": "object",
            "required": [],
            "properties": {
                "origin": {
                    "$ref": "#/definitions/Vector3"
                },
                "up": {
                    "$ref": "#/definitions/Vector3"
                },
                "target": {
                    "$ref": "#/definitions/Vector3"
                },
                "direction": {
                    "$ref": "#/definitions/Vector3"
                }
            }
        },
        "Size": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "Vector3": {
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {
                "type": "number"
            }
        },
        "Vector4": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x3": {
            "type": "array",
            "minItems": 9,
            "maxItems": 9,
            "items": {
                "type": "number"
            }
        },
        "Matrix3x4": {
            "type": "array",
            "minItems": 12,
            "maxItems": 12,
            "items": {
                "type": "number"
            }
        },
        "Matrix4x4": {
            "type": "array",
            "minItems": 16,
            "maxItems": 16,
            "items": {
                "type": "number"
            }
        }
    }
}

=== PearCoding/Ignis/scenes/displacement.json
{
	"technique": {
		"type": "path",
		"max_depth": 2
	},
	"camera": {
		"type": "perspective",
		"fov": 60,
		"near_clip": 0.01,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,0,1,-4, 0,1,0,0 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "env",
			"filename": "textures/environment/phalzer_forest_01_4k.exr"
		},
		{
			"type": "bitmap",
			"name": "metalplates_color",
			"filename": "textures/MetalPlates006_Color.png"
		},
		{
			"type": "bitmap",
			"name": "metalplates_displacement",
			"filename": "textures/MetalPlates006_Displacement.png"
		},
		{
			"type": "bitmap",
			"name": "metalplates_metalness",
			"filename": "textures/MetalPlates006_Metalness.png"
		},
		{
			"type": "bitmap",
			"name": "metalplates_normal",
			"filename": "textures/MetalPlates006_Normal.png"
		},
		{
			"type": "bitmap",
			"name": "metalplates_roughness",
			"filename": "textures/MetalPlates006_Roughness.png"
		},
		{
			"type": "bitmap",
			"name": "wood_color",
			"filename": "textures/Wood047_Color.png"
		},
		{
			"type": "bitmap",
			"name": "wood_displacement",
			"filename": "textures/Wood047_Displacement.png"
		},
		{
			"type": "bitmap",
			"name": "wood_normal",
			"filename": "textures/Wood047_Normal.png"
		},
		{
			"type": "bitmap",
			"name": "wood_roughness",
			"filename": "textures/Wood047_Roughness.png"
		}
	],
	"bsdfs": [
		{"type":"principled", "name": "ground", "base_color":"wood_color", "roughness": "wood_roughness.r", "metallic": 0},
		{"type":"principled", "name": "object", "base_color":"metalplates_color", "roughness": "metalplates_roughness.r", "metallic": "metalplates_metalness.r"}
	],
	"shapes": [
		{"type":"rectangle", "name":"Bottom", "width":10, "height":8, "refinement": 0.002, "smooth_normals": true, "displacement": "textures/Wood047_Displacement.png", "displacement_amount": 0.1},
		{"type":"icosphere", "name":"Object", "radius":0.9, "generic_uv": true, "subdivision": 4, "smooth_normals": true, "displacement": "textures/MetalPlates006_Displacement.png", "displacement_amount": 0.1}
	],
	"entities": [
		{"name":"Bottom","shape":"Bottom", "bsdf":"ground", "transform": [{"translate":[0,0,-0.9]}]},
		{"name":"Object","shape":"Object", "bsdf":"object"}
	],
	"lights": [
		{"type":"env", "name":"Sky", "radiance": "env", "transform": [1,0,0, 0,0,1, 0,1,0]}
	]
}

=== PearCoding/Ignis/scenes/time_plane.json
{
	"technique": {
		"type": "path",
		"max_depth": 4
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ -1,0,0,0, 0,1,0,0, 0,0,-1,15, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "env",
			"filename": "textures/environment/phalzer_forest_01_4k.exr"
		},
		{
			"type": "checkerboard",
			"name": "check",
			"scale_x": 10,
			"scale_y": 10,
			"color0": [0,0,0],
			"color1": [1,1,1]
		},
		{
			"type": "bitmap",
			"name": "mask",
			"filename": "textures/mask.png"
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Fallback"},
		{"type":"diffuse", "name": "mat-Floor", "reflectance":"check"},
		{"type":"diffuse", "name": "mat-Plane", "reflectance":"color(0.1, 0.4, 1)*check(uv+vec2(t*0.2, t*0.1))"}
	],
	"shapes": [
		{"type":"rectangle", "name":"Floor", "width": 10, "height": 10},
		{"type":"box", "name":"Plane", "width": 4, "height": 4, "depth": 0.1}
	],
	"entities": [
		{"name":"Floor","shape":"Floor", "bsdf":"mat-Floor"},
		{"name":"Plane","shape":"Plane", "bsdf":"mat-Plane", "transform": [{"rotate": [0,0,45]}, {"translate": [0,0,2]}]}
	],
	"lights": [
		{"type":"env", "name":"Sky", "radiance": "env", "transform": [1,0,0, 0,0,1, 0,1,0]}
	]
}

=== PearCoding/Ignis/scenes/voronoi_plane.json
{
	"technique": {
		"type": "path",
		"max_depth": 4
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ -1,0,0,0, 0,1,0,0, 0,0,-1,4.5, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "bitmap",
			"name": "env",
			"filename": "textures/environment/phalzer_forest_01_4k.exr"
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "Mat001", "reflectance":"cvoronoi(15*uv, 42, 1, 'f1', 'euclidean')" },
		{"type":"diffuse", "name": "Mat002", "reflectance":"cvoronoi(15*uv, 42, 1, 'f1', 'manhatten')" },
		{"type":"diffuse", "name": "Mat003", "reflectance":"cvoronoi(15*uv, 42, 1, 'f1', 'chebyshev')" },
		{"type":"diffuse", "name": "Mat004", "reflectance":"cvoronoi(15*uv, 42, 1, 'f1', 'minkowski', 42)" },
		{"type":"diffuse", "name": "Mat005", "reflectance":"cvoronoi(15*uv, 42, 1, 'f2', 'euclidean')" },
		{"type":"diffuse", "name": "Mat006", "reflectance":"cvoronoi(15*uv, 42, 1, 'f2', 'manhatten')" },
		{"type":"diffuse", "name": "Mat007", "reflectance":"cvoronoi(15*uv, 42, 1, 'f2', 'chebyshev')" },
		{"type":"diffuse", "name": "Mat008", "reflectance":"cvoronoi(15*uv, 42, 1, 'f2', 'minkowski', 42)" },
		{"type":"diffuse", "name": "Mat009", "reflectance":"cvoronoi(15*uv, 42, 0, 'f1', 'euclidean')" }
	],
	"shapes": [
		{"type":"rectangle", "name":"Plane", "width": 1, "height": 1}
	],
	"entities": [
		{"name":"Plane001","shape":"Plane", "bsdf":"Mat001", "transform": [{"translate": [-1.05,-1.05,0]}]},
		{"name":"Plane002","shape":"Plane", "bsdf":"Mat002", "transform": [{"translate": [ 0.00,-1.05,0]}]},
		{"name":"Plane003","shape":"Plane", "bsdf":"Mat003", "transform": [{"translate": [ 1.05,-1.05,0]}]},
		{"name":"Plane004","shape":"Plane", "bsdf":"Mat004", "transform": [{"translate": [-1.05, 0.00,0]}]},
		{"name":"Plane005","shape":"Plane", "bsdf":"Mat005", "transform": [{"translate": [ 0.00, 0.00,0]}]},
		{"name":"Plane006","shape":"Plane", "bsdf":"Mat006", "transform": [{"translate": [ 1.05, 0.00,0]}]},
		{"name":"Plane007","shape":"Plane", "bsdf":"Mat007", "transform": [{"translate": [-1.05, 1.05,0]}]},
		{"name":"Plane008","shape":"Plane", "bsdf":"Mat008", "transform": [{"translate": [ 0.00, 1.05,0]}]},
		{"name":"Plane009","shape":"Plane", "bsdf":"Mat009", "transform": [{"translate": [ 1.05, 1.05,0]}]}
	],
	"lights": [
		{"type":"env", "name":"Sky", "radiance": "env", "transform": [1,0,0, 0,0,1, 0,1,0]}
	]
}

=== PearCoding/Ignis/scenes/flipped_prim.json
{
	"technique": {
		"type": "path",
		"max_depth": 2
	},
	"camera": {
		"type": "perspective",
		"fov": 60,
		"near_clip": 0.01,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,0,1,-8, 0,1,0,0 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"diffuse", "name": "base", "reflectance":[0.8, 0.8, 0.8]}
	],
	"shapes": [
		{"type":"cylinder", "name":"Object", "transform": [1,0,0,0, 0,1,0,0, 0,0,-1,0]}
	],
	"entities": [
		{"name":"Object","shape":"Object", "bsdf":"base"}
	],
	"lights": [
		{"type":"env", "name":"Light", "radiance":[1,1,1]}
	]
}

=== PearCoding/Ignis/scenes/showcase/bsdf/base.json
{
	"technique": {
		"type": "path",
		"max_depth": 8,
		"clamp": 100
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,0,1,-6, 0,1,0,1.5, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "checkerboard",
			"name": "check",
			"scale_x": 10,
			"scale_y": 10,
			"color0": [0.3,0.3,0.3],
			"color1": [1,1,1]
		},
		{
			"type": "image",
			"name": "env",
			"filename": "../../textures/environment/phalzer_forest_01_4k.exr"
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Ground", "reflectance":"check"},
		{"type":"diffuse", "name": "mat-Socket", "reflectance":[0.8,0.8,0.8]}
	],
	"shapes": [
		{"type":"rectangle", "name":"Ground", "width":10, "height":10},
		{"type":"ply", "name":"Sphere", "filename":"../../meshes/IgnisSphere.ply"},
		{"type":"ply", "name":"Socket", "filename":"../../meshes/IgnisSocket.ply", "flip_normals": true}
	],
	"entities": [
		{"name":"Ground","shape":"Ground", "bsdf":"mat-Ground"},
		{"name":"Socket","shape":"Socket", "bsdf":"mat-Socket"},
		{"name":"Sphere","shape":"Sphere", "bsdf":"mat-Sphere"}
	],
	"lights": [
		{"type":"env", "name":"Environment", "radiance":"env", "transform": [0,-1,0, 0,0,1, 1,0,0]}
	]
}

=== PearCoding/Ignis/scenes/furnance.json
{
	"technique": {
		"type": "path",
		"max_depth": 64
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [ 1,0,0,0, 0,1,0,0, 0,0,1,-4, 0,0,0,1 ]
	},
	"film": {
		"size": [1000, 1000]
	},
	"bsdfs": [
		{"type":"principled", "name": "mat-Sphere", "base_color": [1,1,1], "ior": 1, "roughness": 0.5, "thin": true, "flatness":1}
	],
	"shapes": [
		{"type":"ply", "name":"Sphere", "filename":"meshes/Sphere.ply"}
	],
	"entities": [
		{"name":"Sphere","shape":"Sphere", "bsdf":"mat-Sphere"}
	],
	"lights": [
		{"type":"constant", "name":"Environment", "radiance":1}
	]
}

=== PearCoding/Ignis/scenes/showcase/shape/base.json
{
	"technique": {
		"type": "path",
		"max_depth": 8,
		"clamp": 100
	},
	"camera": {
		"type": "perspective",
		"fov": 40,
		"near_clip": 0.1,
		"far_clip": 100,
		"transform": [{"lookat": { "origin": [ 0,-6,4 ], "target": [0,0,0] } }]
	},
	"film": {
		"size": [1000, 1000]
	},
	"textures": [
		{
			"type": "image",
			"name": "env",
			"filename": "../../textures/environment/phalzer_forest_01_4k.exr"
		}
	],
	"bsdfs": [
		{"type":"diffuse", "name": "mat-Object", "reflectance":"vec3(prim_coords.x, prim_coords.y, 0)"}
	],
	"entities": [
		{"name":"Object","shape":"Object", "bsdf":"mat-Object"}
	],
	"lights": [
		{"type":"env", "name":"Environment", "radiance":"env", "transform": [0,-1,0, 0,0,1, 1,0,0]}
	]
}

=== PearCoding/Ignis/scenes/evaluation/cycles-sun.json
{
  "technique": {
    "type": "path",
    "max_depth": 12,
    "clamp": 0.0
  },
  "camera": {
    "type": "perspective",
    "fov": 39.597752709049864,
    "near_clip": 0.10000000149011612,
    "far_clip": 100.0,
    "transform": [
      -0.6859207153320312,
      -0.32401347160339355,
      -0.6515582203865051,
      5.582485198974609,
      -0.7276763319969177,
      0.3054208755493164,
      0.6141703724861145,
      -5.251318454742432,
      4.011331711240018e-09,
      0.8953956365585327,
      -0.44527146220207214,
      3.7443222999572754,
      0.0,
      0.0,
      0.0,
      1.0
    ]
  },
  "film": {
    "size": [
      256.0,
      256.0
    ]
  },
  "shapes": [
    {
      "type": "ply",
      "name": "GroundSun",
      "filename": "meshes/GroundSun.ply"
    },
    {
      "type": "ply",
      "name": "Cone",
      "filename": "meshes/Cone.ply"
    }
  ],
  "bsdfs": [
    {
      "type": "diffuse",
      "name": "Ground",
      "reflectance": "select(checkerboard(uvw * 5.0) == 1, color(0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0), color(0.20000000298023224, 0.20000000298023224, 0.20000000298023224, 1.0))"
    },
    {
      "type": "principled",
      "name": "Cone",
      "base_color": "color(0.23790551722049713, 0.5817709565162659, 0.8000000715255737, 1.0)",
      "metallic": 0.0,
      "roughness": 0.5,
      "anisotropic": 0.0,
      "sheen": 0.0,
      "sheen_tint": 0.5,
      "clearcoat": 0.0,
      "clearcoat_roughness": 0.029999999329447746,
      "flatness": 0.0,
      "specular_transmission": 0.0,
      "specular_tint": 0.0,
      "reflective_ior": 1.5,
      "refractive_ior": 1.4500000476837158
    }
  ],
  "entities": [
    {
      "name": "GroundSun-GroundSun",
      "shape": "GroundSun",
      "bsdf": "Ground",
      "transform": [
        5.0,
        0.0,
        0.0,
        0.0,
        0.0,
        5.0,
        0.0,
        0.0,
        0.0,
        0.0,
        5.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "shadow_visible": true
    },
    {
      "name": "Cone-Cone",
      "shape": "Cone",
      "bsdf": "Cone",
      "transform": [
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "shadow_visible": true
    }
  ],
  "lights": [
    {
      "type": "sun",
      "name": "Light",
      "direction": [
        -0.8549205660820007,
        -0.13264977931976318,
        -0.5015125870704651
      ],
      "irradiance": [
        100.0,
        74.08868670463562,
        33.32301378250122
      ],
      "angle": 11.421186198001447
    }
  ]
}
